### PR TITLE
nhlist: function for extending TBFs that were killed due to low popul…

### PR DESCRIPTION
**Pull request by nhlist**
…ation to full simulation length

### CODE REVIEW

**Comment by nhlist** [comment]
I have not touched CONTRIBUTING.md but markdown_checks complains about the following
ERROR   -  Error reading page 'CONTRIBUTING.md': wrap() missing 1 required positional argument: 'outfile'

**Comment by coltonbh** [comment]
@nhlist go ahead and merge in. This is a dependencies issue that I haven't had time to fix yet. It's not core to your commit so let's go ahead with the merge.

**Review by coltonbh — APPROVED** [review]
Thanks for the great function documentation! Makes it so much easier to develop in the future :)

**Comment by nhlist** [comment]
@coltonbh Merging is blocked for me due to the markdown error.

**Comment by nhlist** [comment]
Note that I added another improvement.

**Comment by coltonbh** [comment]
Merged!

**Pull request merged**
